server:
  port: 8080
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: Loki@123
   
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect

  application:
   name: Order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
      instance:
      preferIpAddress: true
  
  
